# 博客文章链接格式
permalink:     /:year/:month/:day/:title.html
pygments:    true

# 用 markdown 写
markdown:      redcarpet
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

excerpt_separator: "\n\n"

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
url:         http://localhost:4000
lsi:         false

kramdown:
  input: GFM

# 作者信息
author:                                     
  name: Coffee
  email: coffee.zyr@gmail.com
  link: http://coffeechou.github.io

# 站点信息
title: Coffee 的博客
descprition: Coffee's blog
url: http://coffeechou.github.io

# 还不知道是什么
locals:                                  
  tags: 标签
  about: 关于
active: 技术

# 头像
                       
