# auth0r
keywords: ["blog", "jekyll"]

# Jekyll configuration
plugins: [jekyll-paginate]
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /:year-:month-:day/:title
paginate: 5

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false


# Site Owner configuration
owner:
  name: CoffeeChou
  avatar: jidi-1.jpg
  job: "一只喵，有时画画，常常锻炼，总是发呆"
  bio: |
    我们终其一生，都在寻找幸福的路。  
    --寂地
  email: coffee.zyr@gmail.com
  disqus-shortname: coffeechou
  github: coffeechou
  rss: feed.xml
