source:      .
destination: ./_site
layouts:     ./_layouts
#include:     ['.htaccess']
#exclude:     []
#keep_files:  ['.git','.svn']
#timezone:    nil
encoding:    utf-8

future:      true
show_drafts: nil
limit_posts: 0
pygments:    true

relative_permalinks: true

permalink:     /:year/:month/:day/:title.html    # 博客文章的固定链接
#paginate_path: 'page:num'

markdown:      redcarpet
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

excerpt_separator: "\n\n"

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
url:         http://localhost:4000
lsi:         false

#maruku:
#  use_tex:    false
#  use_divs:   false
#  png_engine: blahtex
#  png_dir:    images/latex
#  png_url:    /images/latex

rdiscount:
  extensions: []

redcarpet:
  extensions: []

#kramdown:
#  auto_ids: true
#  footnote_nr: 1
#  entity_output: as_char
#  toc_levels: 1..6
#  smart_quotes: lsquo,rsquo,ldquo,rdquo
#  use_coderay: false

#  coderay:
#    coderay_wrap: div
#    coderay_line_numbers: inline
#    coderay_line_numbers_start: 1
#    coderay_tab_width: 4
#    coderay_bold_every: 10
#    coderay_css: style

redcloth:
  hard_breaks: true

author:                                     #自定义常亮
  name: Coffee
  email: coffee.zyr@gmail.com
title: Coffee 的博客                             #自定义常量
locals:                                     #自定义常量
  tags: 标签
  about: 关于
active: 技术                                 #自定义常量
