permalink: /:year/:month/:day/:title.html
rouge: true

# 作者信息
author:
  name: Coffee
  email: coffee.zyr@gmail.com

# 使用 markdown 格式
markdown: redcarpet
redcarpet:
  extensions: ["tables", "highlight"]

# disqus 设置
disqus:
  shortname: coffeechou
